
FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.1

RUN yum install -y wget

RUN rm -rf /usr/share/elasticsearch/data/*
RUN wget https://fntest:F3n735t_da7a@ui.nexus.crint.net/repository/fntest_data/fntest-elasticdump-7.x.tgz -O /usr/share/elasticsearch/data/fntest-elasticdump-7.x.tgz
RUN tar -zxvf /usr/share/elasticsearch/data/fntest-elasticdump-7.x.tgz --strip-components=1 -C /usr/share/elasticsearch/data/
RUN rm -f /usr/share/elasticsearch/data/fntest-elasticdump-7.x.tgz
RUN chown -R 1000:1000 /usr/share/elasticsearch/data